name: CI
on:
  pull_request:
    branches:
      - main
jobs:
  flutter_test:
    name: Run flutter test and analyze
    runs-on: ubuntu-latest
    steps:
      - uses : actions/checkout@v4.1.1
      - uses : actions/setup-java@v4.0.0
        with:
          distribution: 'temurin'
          java-version: "17"
      - uses : subosito/flutter-action@v2.12.0
        with:
          channel: "stable"
      - run: flutter pub get
      - run: flutter analyze
      - run: flutter test
